import { z } from 'zod';
import { PersonType } from '../enums/person-type.enum';
import { CustomerSegment } from '../enums/customer-segment.enum';
import { DocumentType } from '../enums/document-type.enum';
import { SubscriberStatus } from '../enums/subscriber-status.enum';
/**
 * Schema Zod para crear suscriptor — persona natural.
 * Campos obligatorios: documentType, documentNumber, firstName, lastName, stratum.
 */
export declare const naturalSubscriberSchema: z.ZodObject<{
    personType: z.ZodLiteral<PersonType.NATURAL>;
    customerSegment: z.ZodNativeEnum<typeof CustomerSegment>;
    documentType: z.ZodNativeEnum<typeof DocumentType>;
    documentNumber: z.ZodString;
    firstName: z.ZodString;
    lastName: z.ZodString;
    stratum: z.ZodNumber;
    birthDate: z.ZodOptional<z.ZodString>;
    email: z.ZodString;
    phone: z.ZodString;
    altContactName: z.ZodOptional<z.ZodString>;
    altContactPhone: z.ZodOptional<z.ZodString>;
    whatsapp: z.ZodOptional<z.ZodString>;
    address: z.ZodString;
    neighborhood: z.ZodOptional<z.ZodString>;
    city: z.ZodOptional<z.ZodString>;
    department: z.ZodOptional<z.ZodString>;
    postalCode: z.ZodOptional<z.ZodString>;
    latitude: z.ZodOptional<z.ZodNumber>;
    longitude: z.ZodOptional<z.ZodNumber>;
    coverageNodeId: z.ZodOptional<z.ZodString>;
    externalId: z.ZodOptional<z.ZodString>;
    expedienteId: z.ZodOptional<z.ZodString>;
    manualOverrideReason: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    email: string;
    personType: PersonType.NATURAL;
    customerSegment: CustomerSegment;
    documentType: DocumentType;
    documentNumber: string;
    firstName: string;
    lastName: string;
    stratum: number;
    phone: string;
    address: string;
    birthDate?: string | undefined;
    altContactName?: string | undefined;
    altContactPhone?: string | undefined;
    whatsapp?: string | undefined;
    neighborhood?: string | undefined;
    city?: string | undefined;
    department?: string | undefined;
    postalCode?: string | undefined;
    latitude?: number | undefined;
    longitude?: number | undefined;
    coverageNodeId?: string | undefined;
    externalId?: string | undefined;
    expedienteId?: string | undefined;
    manualOverrideReason?: string | undefined;
}, {
    email: string;
    personType: PersonType.NATURAL;
    customerSegment: CustomerSegment;
    documentType: DocumentType;
    documentNumber: string;
    firstName: string;
    lastName: string;
    stratum: number;
    phone: string;
    address: string;
    birthDate?: string | undefined;
    altContactName?: string | undefined;
    altContactPhone?: string | undefined;
    whatsapp?: string | undefined;
    neighborhood?: string | undefined;
    city?: string | undefined;
    department?: string | undefined;
    postalCode?: string | undefined;
    latitude?: number | undefined;
    longitude?: number | undefined;
    coverageNodeId?: string | undefined;
    externalId?: string | undefined;
    expedienteId?: string | undefined;
    manualOverrideReason?: string | undefined;
}>;
/**
 * Schema Zod para crear suscriptor — persona jurídica.
 * Campos obligatorios: nit, businessName.
 */
export declare const juridicaSubscriberSchema: z.ZodObject<{
    personType: z.ZodLiteral<PersonType.JURIDICA>;
    customerSegment: z.ZodNativeEnum<typeof CustomerSegment>;
    nit: z.ZodString;
    nitVerificationDigit: z.ZodOptional<z.ZodString>;
    businessName: z.ZodString;
    commercialName: z.ZodOptional<z.ZodString>;
    legalRepresentativeId: z.ZodOptional<z.ZodString>;
    email: z.ZodString;
    phone: z.ZodString;
    altContactName: z.ZodOptional<z.ZodString>;
    altContactPhone: z.ZodOptional<z.ZodString>;
    whatsapp: z.ZodOptional<z.ZodString>;
    address: z.ZodString;
    neighborhood: z.ZodOptional<z.ZodString>;
    city: z.ZodOptional<z.ZodString>;
    department: z.ZodOptional<z.ZodString>;
    postalCode: z.ZodOptional<z.ZodString>;
    latitude: z.ZodOptional<z.ZodNumber>;
    longitude: z.ZodOptional<z.ZodNumber>;
    coverageNodeId: z.ZodOptional<z.ZodString>;
    externalId: z.ZodOptional<z.ZodString>;
    expedienteId: z.ZodOptional<z.ZodString>;
    manualOverrideReason: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    email: string;
    personType: PersonType.JURIDICA;
    customerSegment: CustomerSegment;
    phone: string;
    address: string;
    nit: string;
    businessName: string;
    altContactName?: string | undefined;
    altContactPhone?: string | undefined;
    whatsapp?: string | undefined;
    neighborhood?: string | undefined;
    city?: string | undefined;
    department?: string | undefined;
    postalCode?: string | undefined;
    latitude?: number | undefined;
    longitude?: number | undefined;
    coverageNodeId?: string | undefined;
    externalId?: string | undefined;
    expedienteId?: string | undefined;
    manualOverrideReason?: string | undefined;
    nitVerificationDigit?: string | undefined;
    commercialName?: string | undefined;
    legalRepresentativeId?: string | undefined;
}, {
    email: string;
    personType: PersonType.JURIDICA;
    customerSegment: CustomerSegment;
    phone: string;
    address: string;
    nit: string;
    businessName: string;
    altContactName?: string | undefined;
    altContactPhone?: string | undefined;
    whatsapp?: string | undefined;
    neighborhood?: string | undefined;
    city?: string | undefined;
    department?: string | undefined;
    postalCode?: string | undefined;
    latitude?: number | undefined;
    longitude?: number | undefined;
    coverageNodeId?: string | undefined;
    externalId?: string | undefined;
    expedienteId?: string | undefined;
    manualOverrideReason?: string | undefined;
    nitVerificationDigit?: string | undefined;
    commercialName?: string | undefined;
    legalRepresentativeId?: string | undefined;
}>;
/**
 * Schema Zod con unión discriminada por personType.
 * Valida campos obligatorios según tipo de persona.
 */
export declare const CreateSubscriberSchema: z.ZodDiscriminatedUnion<"personType", [z.ZodObject<{
    personType: z.ZodLiteral<PersonType.NATURAL>;
    customerSegment: z.ZodNativeEnum<typeof CustomerSegment>;
    documentType: z.ZodNativeEnum<typeof DocumentType>;
    documentNumber: z.ZodString;
    firstName: z.ZodString;
    lastName: z.ZodString;
    stratum: z.ZodNumber;
    birthDate: z.ZodOptional<z.ZodString>;
    email: z.ZodString;
    phone: z.ZodString;
    altContactName: z.ZodOptional<z.ZodString>;
    altContactPhone: z.ZodOptional<z.ZodString>;
    whatsapp: z.ZodOptional<z.ZodString>;
    address: z.ZodString;
    neighborhood: z.ZodOptional<z.ZodString>;
    city: z.ZodOptional<z.ZodString>;
    department: z.ZodOptional<z.ZodString>;
    postalCode: z.ZodOptional<z.ZodString>;
    latitude: z.ZodOptional<z.ZodNumber>;
    longitude: z.ZodOptional<z.ZodNumber>;
    coverageNodeId: z.ZodOptional<z.ZodString>;
    externalId: z.ZodOptional<z.ZodString>;
    expedienteId: z.ZodOptional<z.ZodString>;
    manualOverrideReason: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    email: string;
    personType: PersonType.NATURAL;
    customerSegment: CustomerSegment;
    documentType: DocumentType;
    documentNumber: string;
    firstName: string;
    lastName: string;
    stratum: number;
    phone: string;
    address: string;
    birthDate?: string | undefined;
    altContactName?: string | undefined;
    altContactPhone?: string | undefined;
    whatsapp?: string | undefined;
    neighborhood?: string | undefined;
    city?: string | undefined;
    department?: string | undefined;
    postalCode?: string | undefined;
    latitude?: number | undefined;
    longitude?: number | undefined;
    coverageNodeId?: string | undefined;
    externalId?: string | undefined;
    expedienteId?: string | undefined;
    manualOverrideReason?: string | undefined;
}, {
    email: string;
    personType: PersonType.NATURAL;
    customerSegment: CustomerSegment;
    documentType: DocumentType;
    documentNumber: string;
    firstName: string;
    lastName: string;
    stratum: number;
    phone: string;
    address: string;
    birthDate?: string | undefined;
    altContactName?: string | undefined;
    altContactPhone?: string | undefined;
    whatsapp?: string | undefined;
    neighborhood?: string | undefined;
    city?: string | undefined;
    department?: string | undefined;
    postalCode?: string | undefined;
    latitude?: number | undefined;
    longitude?: number | undefined;
    coverageNodeId?: string | undefined;
    externalId?: string | undefined;
    expedienteId?: string | undefined;
    manualOverrideReason?: string | undefined;
}>, z.ZodObject<{
    personType: z.ZodLiteral<PersonType.JURIDICA>;
    customerSegment: z.ZodNativeEnum<typeof CustomerSegment>;
    nit: z.ZodString;
    nitVerificationDigit: z.ZodOptional<z.ZodString>;
    businessName: z.ZodString;
    commercialName: z.ZodOptional<z.ZodString>;
    legalRepresentativeId: z.ZodOptional<z.ZodString>;
    email: z.ZodString;
    phone: z.ZodString;
    altContactName: z.ZodOptional<z.ZodString>;
    altContactPhone: z.ZodOptional<z.ZodString>;
    whatsapp: z.ZodOptional<z.ZodString>;
    address: z.ZodString;
    neighborhood: z.ZodOptional<z.ZodString>;
    city: z.ZodOptional<z.ZodString>;
    department: z.ZodOptional<z.ZodString>;
    postalCode: z.ZodOptional<z.ZodString>;
    latitude: z.ZodOptional<z.ZodNumber>;
    longitude: z.ZodOptional<z.ZodNumber>;
    coverageNodeId: z.ZodOptional<z.ZodString>;
    externalId: z.ZodOptional<z.ZodString>;
    expedienteId: z.ZodOptional<z.ZodString>;
    manualOverrideReason: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    email: string;
    personType: PersonType.JURIDICA;
    customerSegment: CustomerSegment;
    phone: string;
    address: string;
    nit: string;
    businessName: string;
    altContactName?: string | undefined;
    altContactPhone?: string | undefined;
    whatsapp?: string | undefined;
    neighborhood?: string | undefined;
    city?: string | undefined;
    department?: string | undefined;
    postalCode?: string | undefined;
    latitude?: number | undefined;
    longitude?: number | undefined;
    coverageNodeId?: string | undefined;
    externalId?: string | undefined;
    expedienteId?: string | undefined;
    manualOverrideReason?: string | undefined;
    nitVerificationDigit?: string | undefined;
    commercialName?: string | undefined;
    legalRepresentativeId?: string | undefined;
}, {
    email: string;
    personType: PersonType.JURIDICA;
    customerSegment: CustomerSegment;
    phone: string;
    address: string;
    nit: string;
    businessName: string;
    altContactName?: string | undefined;
    altContactPhone?: string | undefined;
    whatsapp?: string | undefined;
    neighborhood?: string | undefined;
    city?: string | undefined;
    department?: string | undefined;
    postalCode?: string | undefined;
    latitude?: number | undefined;
    longitude?: number | undefined;
    coverageNodeId?: string | undefined;
    externalId?: string | undefined;
    expedienteId?: string | undefined;
    manualOverrideReason?: string | undefined;
    nitVerificationDigit?: string | undefined;
    commercialName?: string | undefined;
    legalRepresentativeId?: string | undefined;
}>]>;
/**
 * Schema Zod para actualizar suscriptor — todos los campos opcionales.
 * Si se cambia personType o stratum, se recalcula vatTreatment automáticamente.
 */
export declare const UpdateSubscriberSchema: z.ZodObject<{
    personType: z.ZodOptional<z.ZodNativeEnum<typeof PersonType>>;
    customerSegment: z.ZodOptional<z.ZodNativeEnum<typeof CustomerSegment>>;
    documentType: z.ZodOptional<z.ZodNativeEnum<typeof DocumentType>>;
    documentNumber: z.ZodOptional<z.ZodString>;
    firstName: z.ZodOptional<z.ZodString>;
    lastName: z.ZodOptional<z.ZodString>;
    stratum: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    birthDate: z.ZodOptional<z.ZodString>;
    nit: z.ZodOptional<z.ZodString>;
    nitVerificationDigit: z.ZodOptional<z.ZodString>;
    businessName: z.ZodOptional<z.ZodString>;
    commercialName: z.ZodOptional<z.ZodString>;
    legalRepresentativeId: z.ZodOptional<z.ZodString>;
    email: z.ZodOptional<z.ZodString>;
    phone: z.ZodOptional<z.ZodString>;
    altContactName: z.ZodOptional<z.ZodString>;
    altContactPhone: z.ZodOptional<z.ZodString>;
    whatsapp: z.ZodOptional<z.ZodString>;
    address: z.ZodOptional<z.ZodString>;
    neighborhood: z.ZodOptional<z.ZodString>;
    city: z.ZodOptional<z.ZodString>;
    department: z.ZodOptional<z.ZodString>;
    postalCode: z.ZodOptional<z.ZodString>;
    latitude: z.ZodOptional<z.ZodNumber>;
    longitude: z.ZodOptional<z.ZodNumber>;
    coverageNodeId: z.ZodOptional<z.ZodString>;
    externalId: z.ZodOptional<z.ZodString>;
    expedienteId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    manualOverrideReason: z.ZodOptional<z.ZodNullable<z.ZodString>>;
}, "strip", z.ZodTypeAny, {
    email?: string | undefined;
    personType?: PersonType | undefined;
    customerSegment?: CustomerSegment | undefined;
    documentType?: DocumentType | undefined;
    documentNumber?: string | undefined;
    firstName?: string | undefined;
    lastName?: string | undefined;
    stratum?: number | null | undefined;
    birthDate?: string | undefined;
    phone?: string | undefined;
    altContactName?: string | undefined;
    altContactPhone?: string | undefined;
    whatsapp?: string | undefined;
    address?: string | undefined;
    neighborhood?: string | undefined;
    city?: string | undefined;
    department?: string | undefined;
    postalCode?: string | undefined;
    latitude?: number | undefined;
    longitude?: number | undefined;
    coverageNodeId?: string | undefined;
    externalId?: string | undefined;
    expedienteId?: string | null | undefined;
    manualOverrideReason?: string | null | undefined;
    nit?: string | undefined;
    nitVerificationDigit?: string | undefined;
    businessName?: string | undefined;
    commercialName?: string | undefined;
    legalRepresentativeId?: string | undefined;
}, {
    email?: string | undefined;
    personType?: PersonType | undefined;
    customerSegment?: CustomerSegment | undefined;
    documentType?: DocumentType | undefined;
    documentNumber?: string | undefined;
    firstName?: string | undefined;
    lastName?: string | undefined;
    stratum?: number | null | undefined;
    birthDate?: string | undefined;
    phone?: string | undefined;
    altContactName?: string | undefined;
    altContactPhone?: string | undefined;
    whatsapp?: string | undefined;
    address?: string | undefined;
    neighborhood?: string | undefined;
    city?: string | undefined;
    department?: string | undefined;
    postalCode?: string | undefined;
    latitude?: number | undefined;
    longitude?: number | undefined;
    coverageNodeId?: string | undefined;
    externalId?: string | undefined;
    expedienteId?: string | null | undefined;
    manualOverrideReason?: string | null | undefined;
    nit?: string | undefined;
    nitVerificationDigit?: string | undefined;
    businessName?: string | undefined;
    commercialName?: string | undefined;
    legalRepresentativeId?: string | undefined;
}>;
/**
 * Schema Zod para transición de estado del suscriptor.
 * reason es obligatorio para SUSPENDED y CANCELLED (validación en UI).
 */
export declare const TransitionSubscriberStatusSchema: z.ZodObject<{
    targetStatus: z.ZodNativeEnum<typeof SubscriberStatus>;
    reason: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    targetStatus: SubscriberStatus;
    reason?: string | undefined;
}, {
    targetStatus: SubscriberStatus;
    reason?: string | undefined;
}>;
export type NaturalSubscriberPayload = z.infer<typeof naturalSubscriberSchema>;
export type JuridicaSubscriberPayload = z.infer<typeof juridicaSubscriberSchema>;
export type CreateSubscriberPayload = z.infer<typeof CreateSubscriberSchema>;
export type UpdateSubscriberPayload = z.infer<typeof UpdateSubscriberSchema>;
export type TransitionStatusPayload = z.infer<typeof TransitionSubscriberStatusSchema>;
//# sourceMappingURL=subscriber.schema.d.ts.map