export enum TaskStatus {
  OPEN = 'OPEN',
  READY = 'READY',
  SCHEDULED = 'SCHEDULED',
  IN_PROGRESS = 'IN_PROGRESS',
  PENDING_EXTERNAL = 'PENDING_EXTERNAL',
  PENDING_INTERNAL = 'PENDING_INTERNAL',
  BLOCKED = 'BLOCKED',
  RESOLVED = 'RESOLVED',
  CANCELLED = 'CANCELLED',
}
