export enum TaskRecipientType {
  SUBSCRIBER = 'SUBSCRIBER',
  PROSPECT = 'PROSPECT',
  INTERNAL_USER = 'INTERNAL_USER',
  INTERNAL_AREA = 'INTERNAL_AREA',
  CONTRACTOR = 'CONTRACTOR',
  EXTERNAL_PARTY = 'EXTERNAL_PARTY',
}
