export enum TaskTimelineEventType {
  CREATED = 'CREATED',
  TASK_CREATED_FROM_TICKET = 'TASK_CREATED_FROM_TICKET',
  ASSIGNED = 'ASSIGNED',
  REASSIGNED = 'REASSIGNED',
  STATUS_CHANGED = 'STATUS_CHANGED',
  SCHEDULE_LINKED = 'SCHEDULE_LINKED',
  WORK_ORDER_LINKED = 'WORK_ORDER_LINKED',
  BLOCKED = 'BLOCKED',
  RESOLVED = 'RESOLVED',
  CANCELLED = 'CANCELLED',
}
