export enum AssetLifecycleEventType {
  RECEIVED = 'RECEIVED',
  TRANSFERRED = 'TRANSFERRED',
  INSTALLED = 'INSTALLED',
  RETURNED = 'RETURNED',
  REPAIRED = 'REPAIRED',
  REFURBISHED = 'REFURBISHED',
  SOLD = 'SOLD',
  CONSUMED = 'CONSUMED',
  WRITTEN_OFF = 'WRITTEN_OFF',
  STATUS_CHANGED = 'STATUS_CHANGED',
}
