export declare enum InventoryDisposition {
    INSTALLED_AT_CUSTOMER = "INSTALLED_AT_CUSTOMER",
    INTERNAL_CONSUMPTION = "INTERNAL_CONSUMPTION",
    RETURNED_TO_TECHNICIAN_STOCK = "RETURNED_TO_TECHNICIAN_STOCK",
    RETURNED_TO_WAREHOUSE = "RETURNED_TO_WAREHOUSE",
    DAMAGED_OR_LOST = "DAMAGED_OR_LOST"
}
//# sourceMappingURL=inventory-disposition.enum.d.ts.map