export enum PurchaseRequestStatus {
  DRAFT = 'DRAFT',
  PENDING_QUOTES = 'PENDING_QUOTES',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  CONVERTED_TO_PO = 'CONVERTED_TO_PO',
}
