export enum PurchaseRequestLineStatus {
  OPEN = 'OPEN',
  PENDING_QUOTE = 'PENDING_QUOTE',
  AWARDED = 'AWARDED',
  ORDERED = 'ORDERED',
  PARTIALLY_RECEIVED = 'PARTIALLY_RECEIVED',
  RECEIVED = 'RECEIVED',
  CANCELLED = 'CANCELLED',
  REJECTED = 'REJECTED',
}
