export declare enum SerializedAssetStatus {
    ORDERED = "ORDERED",
    IN_RECEIVING = "IN_RECEIVING",
    AVAILABLE = "AVAILABLE",
    ASSIGNED_TO_TECHNICIAN = "ASSIGNED_TO_TECHNICIAN",
    INSTALLED_COMODATO = "INSTALLED_COMODATO",
    SOLD = "SOLD",
    INTERNAL_CONSUMED = "INTERNAL_CONSUMED",
    IN_TRANSIT = "IN_TRANSIT",
    IN_TESTING = "IN_TESTING",
    AVAILABLE_REFURBISHED = "AVAILABLE_REFURBISHED",
    IN_REPAIR = "IN_REPAIR",
    WRITTEN_OFF = "WRITTEN_OFF",
    LOST = "LOST"
}
//# sourceMappingURL=serialized-asset-status.enum.d.ts.map