export declare enum StockLocationType {
    MAIN_WAREHOUSE = "MAIN_WAREHOUSE",
    MOBILE_TECHNICIAN = "MOBILE_TECHNICIAN",
    MOBILE_CREW = "MOBILE_CREW",
    CUSTOMER_SITE = "CUSTOMER_SITE",
    QUARANTINE = "QUARANTINE",
    REPAIR = "REPAIR",
    SCRAP = "SCRAP",
    INTERNAL_CONSUMPTION = "INTERNAL_CONSUMPTION"
}
//# sourceMappingURL=stock-location-type.enum.d.ts.map