export enum StockIssueType {
  TECHNICIAN_CUSTODY = 'TECHNICIAN_CUSTODY',
  CREW_CUSTODY = 'CREW_CUSTODY',
  OFFICE_REPLENISHMENT = 'OFFICE_REPLENISHMENT',
  NODE_REPLENISHMENT = 'NODE_REPLENISHMENT',
  SALE_DISPATCH = 'SALE_DISPATCH',
  INTERNAL_CONSUMPTION = 'INTERNAL_CONSUMPTION',
  WAREHOUSE_TO_WAREHOUSE = 'WAREHOUSE_TO_WAREHOUSE',
}
