export enum StockMovementOrigin {
  PURCHASE_RECEIPT = 'PURCHASE_RECEIPT',
  TRANSFER = 'TRANSFER',
  EXECUTION_ORDER = 'EXECUTION_ORDER',
  EXECUTION_ORDER_REVERSAL = 'EXECUTION_ORDER_REVERSAL',
  SALE = 'SALE',
  INTERNAL_CONSUMPTION = 'INTERNAL_CONSUMPTION',
  RETURN = 'RETURN',
  REFURBISH = 'REFURBISH',
  ADJUSTMENT = 'ADJUSTMENT',
  WRITE_OFF = 'WRITE_OFF',
  COUNTER_PURCHASE = 'COUNTER_PURCHASE',
}
