packages:
  - 'apps/*'
  - 'packages/*'
useNodeVersion: 24.13.1

onlyBuiltDependencies:
  - '@nestjs/core'
  - 'msgpackr-extract'
  - 'sharp'

overrides:
  ioredis: '5.10.0'

allowBuilds:
  '@nestjs/core': set this to true or false
  '@scarf/scarf': set this to true or false
  msgpackr-extract: set this to true or false
  sharp: set this to true or false
