import {
  AccessPermissionAvailability,
  AccessPermissionCatalogVersion,
  AccessPermissionKey,
  UserRole,
} from '@iwana/shared';

interface PermissionSeedDefinition {
  permissionKey: AccessPermissionKey;
  moduleKey: string;
  action: string;
  description: string;
  catalogVersion: AccessPermissionCatalogVersion;
  availability: AccessPermissionAvailability;
}

const version = AccessPermissionCatalogVersion.MOD00_ACCESS_V1;

export const MOD00_ACCESS_V1_CATALOG: PermissionSeedDefinition[] = [
  {
    permissionKey: AccessPermissionKey.SETTINGS_READ,
    moduleKey: 'settings',
    action: 'read',
    description: 'Ver centro de Configuración',
    catalogVersion: version,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.SETTINGS_MANAGE,
    moduleKey: 'settings',
    action: 'manage',
    description: 'Administrar configuración general de MOD00',
    catalogVersion: version,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.ORGANIZATION_SITES_READ,
    moduleKey: 'organization',
    action: 'read',
    description: 'Ver sedes organizacionales',
    catalogVersion: version,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.ORGANIZATION_SITES_MANAGE,
    moduleKey: 'organization',
    action: 'manage',
    description: 'Crear, editar, activar/desactivar y eliminar sedes',
    catalogVersion: version,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.ORGANIZATION_HOURS_MANAGE,
    moduleKey: 'organization',
    action: 'manage',
    description: 'Gestionar horarios institucionales de sedes',
    catalogVersion: version,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.ORGANIZATION_ASSIGNMENTS_MANAGE,
    moduleKey: 'organization',
    action: 'manage',
    description: 'Gestionar asignaciones y responsables de sedes',
    catalogVersion: version,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.USERS_READ,
    moduleKey: 'users',
    action: 'read',
    description: 'Ver usuarios internos del tenant',
    catalogVersion: version,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.USERS_MANAGE,
    moduleKey: 'users',
    action: 'manage',
    description: 'Gestionar usuarios internos desde el contrato aprobado de Users',
    catalogVersion: version,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.ACCESS_PERMISSIONS_READ,
    moduleKey: 'access',
    action: 'read',
    description: 'Ver catálogo de permisos y matriz disponible',
    catalogVersion: version,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.ACCESS_PROFILES_READ,
    moduleKey: 'access',
    action: 'read',
    description: 'Ver perfiles configurables',
    catalogVersion: version,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.ACCESS_PROFILES_MANAGE,
    moduleKey: 'access',
    action: 'manage',
    description: 'Crear, editar y desactivar perfiles configurables',
    catalogVersion: version,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.ACCESS_ASSIGNMENTS_MANAGE,
    moduleKey: 'access',
    action: 'manage',
    description: 'Asignar perfiles de acceso a usuarios del tenant',
    catalogVersion: version,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.WFM_SCHEDULE_READ,
    moduleKey: 'wfm',
    action: 'read',
    description: 'Ver agenda WFM cuando el módulo exponga guard granular',
    catalogVersion: version,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.WFM_SCHEDULE_MANAGE,
    moduleKey: 'wfm',
    action: 'manage',
    description: 'Gestionar agenda WFM cuando el módulo exponga guard granular',
    catalogVersion: version,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.WFM_WORK_ORDERS_EXECUTE,
    moduleKey: 'wfm',
    action: 'execute',
    description: 'Ejecutar work orders asignadas cuando WFM exponga guard granular',
    catalogVersion: version,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.CRM_CUSTOMERS_READ,
    moduleKey: 'crm',
    action: 'read',
    description: 'Ver expedientes CRM en fase futura',
    catalogVersion: version,
    availability: AccessPermissionAvailability.RESERVED,
  },
  {
    permissionKey: AccessPermissionKey.CRM_CUSTOMERS_MANAGE,
    moduleKey: 'crm',
    action: 'manage',
    description: 'Gestionar expedientes CRM en fase futura',
    catalogVersion: version,
    availability: AccessPermissionAvailability.RESERVED,
  },
  {
    permissionKey: AccessPermissionKey.COMMERCIAL_CATALOG_READ,
    moduleKey: 'commercial',
    action: 'read',
    description: 'Ver catálogo comercial en fase futura',
    catalogVersion: version,
    availability: AccessPermissionAvailability.RESERVED,
  },
  {
    permissionKey: AccessPermissionKey.COMMERCIAL_CATALOG_MANAGE,
    moduleKey: 'commercial',
    action: 'manage',
    description: 'Gestionar catálogo comercial en fase futura',
    catalogVersion: version,
    availability: AccessPermissionAvailability.RESERVED,
  },
  {
    permissionKey: AccessPermissionKey.ASSURANCE_TICKETS_READ,
    moduleKey: 'assurance',
    action: 'read',
    description: 'Ver tickets/PQR en fase futura',
    catalogVersion: version,
    availability: AccessPermissionAvailability.RESERVED,
  },
  {
    permissionKey: AccessPermissionKey.ASSURANCE_TICKETS_MANAGE,
    moduleKey: 'assurance',
    action: 'manage',
    description: 'Gestionar tickets/PQR en fase futura',
    catalogVersion: version,
    availability: AccessPermissionAvailability.RESERVED,
  },
  {
    permissionKey: AccessPermissionKey.INVENTORY_STOCK_READ,
    moduleKey: 'inventory',
    action: 'read',
    description: 'Ver inventario futuro',
    catalogVersion: version,
    availability: AccessPermissionAvailability.RESERVED,
  },
  {
    permissionKey: AccessPermissionKey.INVENTORY_STOCK_MANAGE,
    moduleKey: 'inventory',
    action: 'manage',
    description: 'Gestionar inventario futuro',
    catalogVersion: version,
    availability: AccessPermissionAvailability.RESERVED,
  },
  {
    permissionKey: AccessPermissionKey.BILLING_PAYMENTS_READ,
    moduleKey: 'billing',
    action: 'read',
    description: 'Ver recaudos futuros',
    catalogVersion: version,
    availability: AccessPermissionAvailability.RESERVED,
  },
  {
    permissionKey: AccessPermissionKey.BILLING_PAYMENTS_REGISTER,
    moduleKey: 'billing',
    action: 'register',
    description: 'Registrar recaudo futuro',
    catalogVersion: version,
    availability: AccessPermissionAvailability.RESERVED,
  },
  {
    permissionKey: AccessPermissionKey.BILLING_INVOICES_READ,
    moduleKey: 'billing',
    action: 'read',
    description: 'Ver facturas futuras',
    catalogVersion: version,
    availability: AccessPermissionAvailability.RESERVED,
  },
  {
    permissionKey: AccessPermissionKey.BILLING_INVOICES_MANAGE,
    moduleKey: 'billing',
    action: 'manage',
    description: 'Gestionar facturación futura',
    catalogVersion: version,
    availability: AccessPermissionAvailability.RESERVED,
  },
];

export const ROLE_ASSIGNABLE_PERMISSION_MATRIX: Record<UserRole, AccessPermissionKey[]> = {
  [UserRole.ADMIN]: MOD00_ACCESS_V1_CATALOG.filter(
    (entry) => entry.availability === AccessPermissionAvailability.ASSIGNABLE,
  ).map((entry) => entry.permissionKey),
  [UserRole.NOC]: [
    AccessPermissionKey.SETTINGS_READ,
    AccessPermissionKey.ORGANIZATION_SITES_READ,
    AccessPermissionKey.WFM_SCHEDULE_READ,
  ],
  [UserRole.SUPPORT]: [
    AccessPermissionKey.SETTINGS_READ,
    AccessPermissionKey.ORGANIZATION_SITES_READ,
    AccessPermissionKey.USERS_READ,
    AccessPermissionKey.WFM_SCHEDULE_READ,
  ],
  [UserRole.SALES]: [
    AccessPermissionKey.SETTINGS_READ,
    AccessPermissionKey.ORGANIZATION_SITES_READ,
  ],
  [UserRole.TECHNICIAN]: [
    AccessPermissionKey.SETTINGS_READ,
    AccessPermissionKey.ORGANIZATION_SITES_READ,
    AccessPermissionKey.WFM_SCHEDULE_READ,
    AccessPermissionKey.WFM_WORK_ORDERS_EXECUTE,
  ],
  [UserRole.ACCOUNTANT]: [
    AccessPermissionKey.SETTINGS_READ,
    AccessPermissionKey.ORGANIZATION_SITES_READ,
  ],
  [UserRole.HR]: [
    AccessPermissionKey.SETTINGS_READ,
    AccessPermissionKey.ORGANIZATION_SITES_READ,
    AccessPermissionKey.USERS_READ,
  ],
  [UserRole.SUBSCRIBER]: [],
  [UserRole.CONTRACTOR]: [
    AccessPermissionKey.SETTINGS_READ,
    AccessPermissionKey.ORGANIZATION_SITES_READ,
    AccessPermissionKey.WFM_SCHEDULE_READ,
    AccessPermissionKey.WFM_WORK_ORDERS_EXECUTE,
  ],
  [UserRole.PARTNER]: [],
  [UserRole.AUDITOR]: [
    AccessPermissionKey.SETTINGS_READ,
    AccessPermissionKey.ORGANIZATION_SITES_READ,
    AccessPermissionKey.USERS_READ,
    AccessPermissionKey.ACCESS_PERMISSIONS_READ,
    AccessPermissionKey.ACCESS_PROFILES_READ,
  ],
  [UserRole.INVESTOR]: [],
  [UserRole.SYSTEM_ADMIN]: [],
  [UserRole.IWANA_SUPPORT]: [],
};
