import {
  AccessPermissionAvailability,
  AccessPermissionCatalogVersion,
  AccessPermissionKey,
  UserRole,
} from '@iwana/shared';

interface PermissionSeedDefinition {
  permissionKey: AccessPermissionKey;
  moduleKey: string;
  action: string;
  description: string;
  catalogVersion: AccessPermissionCatalogVersion;
  availability: AccessPermissionAvailability;
}

interface SystemRoleTemplateDefinition {
  name: string;
  description: string;
  baseRoleConstraint: UserRole;
  permissionKeys: AccessPermissionKey[];
}

const version = AccessPermissionCatalogVersion.MOD00_ACCESS_V1;
const versionV2 = AccessPermissionCatalogVersion.MOD00_ACCESS_V2;

export const MOD00_ACCESS_V1_CATALOG: PermissionSeedDefinition[] = [
  {
    permissionKey: AccessPermissionKey.SETTINGS_READ,
    moduleKey: 'settings',
    action: 'read',
    description: 'Ver centro de Configuración',
    catalogVersion: version,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.SETTINGS_MANAGE,
    moduleKey: 'settings',
    action: 'manage',
    description: 'Administrar la configuración general',
    catalogVersion: version,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.ORGANIZATION_SITES_READ,
    moduleKey: 'organization',
    action: 'read',
    description: 'Ver sedes de la empresa',
    catalogVersion: version,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.ORGANIZATION_SITES_MANAGE,
    moduleKey: 'organization',
    action: 'manage',
    description: 'Crear, editar, activar/desactivar y eliminar sedes',
    catalogVersion: version,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.ORGANIZATION_HOURS_MANAGE,
    moduleKey: 'organization',
    action: 'manage',
    description: 'Gestionar horarios institucionales de sedes',
    catalogVersion: version,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.ORGANIZATION_ASSIGNMENTS_MANAGE,
    moduleKey: 'organization',
    action: 'manage',
    description: 'Gestionar asignaciones y responsables de sedes',
    catalogVersion: version,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.USERS_READ,
    moduleKey: 'users',
    action: 'read',
    description: 'Ver usuarios internos de la empresa',
    catalogVersion: version,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.USERS_MANAGE,
    moduleKey: 'users',
    action: 'manage',
    description: 'Crear, editar y desactivar usuarios internos',
    catalogVersion: version,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.ACCESS_PERMISSIONS_READ,
    moduleKey: 'access',
    action: 'read',
    description: 'Ver los accesos disponibles para cada perfil',
    catalogVersion: version,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.ACCESS_PROFILES_READ,
    moduleKey: 'access',
    action: 'read',
    description: 'Ver perfiles de acceso',
    catalogVersion: version,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.ACCESS_PROFILES_MANAGE,
    moduleKey: 'access',
    action: 'manage',
    description: 'Crear, editar y desactivar perfiles de acceso',
    catalogVersion: version,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.ACCESS_ASSIGNMENTS_MANAGE,
    moduleKey: 'access',
    action: 'manage',
    description: 'Asignar perfiles de acceso a usuarios de la empresa',
    catalogVersion: version,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.WFM_SCHEDULE_READ,
    moduleKey: 'wfm',
    action: 'read',
    description: 'Ver agenda de visitas',
    catalogVersion: version,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.WFM_SCHEDULE_MANAGE,
    moduleKey: 'wfm',
    action: 'manage',
    description: 'Gestionar agenda de visitas',
    catalogVersion: version,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.WFM_WORK_ORDERS_EXECUTE,
    moduleKey: 'wfm',
    action: 'execute',
    description: 'Ejecutar órdenes de trabajo asignadas',
    catalogVersion: version,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.OPERATIONS_EXECUTION_ORDERS_READ,
    moduleKey: 'operations',
    action: 'read',
    description: 'Consultar órdenes de ejecución asignadas y supervisadas',
    catalogVersion: version,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.OPERATIONS_EXECUTION_ORDERS_EXECUTE,
    moduleKey: 'operations',
    action: 'execute',
    description: 'Ejecutar actividades, evidencias y cierre de órdenes asignadas',
    catalogVersion: version,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.OPERATIONS_EXECUTION_ORDERS_SUPERVISE,
    moduleKey: 'operations',
    action: 'supervise',
    description: 'Asignar y supervisar órdenes de ejecución',
    catalogVersion: version,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.OPERATIONS_EXECUTION_ORDER_TEMPLATES_READ,
    moduleKey: 'operations',
    action: 'read',
    description: 'Consultar plantillas de ejecución',
    catalogVersion: version,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.OPERATIONS_EXECUTION_ORDER_TEMPLATES_MANAGE,
    moduleKey: 'operations',
    action: 'manage',
    description: 'Administrar versiones de plantillas de ejecución',
    catalogVersion: version,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.OPERATIONS_EXECUTION_EVENTS_REDRIVE,
    moduleKey: 'operations',
    action: 'redrive',
    description: 'Reintentar eventos fallidos de ejecución con ticket operativo',
    catalogVersion: version,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.OPERATIONS_TASKS_READ,
    moduleKey: 'operations',
    action: 'read',
    description: 'Ver tareas operativas de la empresa',
    catalogVersion: version,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.OPERATIONS_TASKS_MANAGE,
    moduleKey: 'operations',
    action: 'manage',
    description: 'Crear, asignar y actualizar tareas operativas',
    catalogVersion: version,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.CRM_CUSTOMERS_READ,
    moduleKey: 'crm',
    action: 'read',
    description: 'Ver expedientes CRM en fase futura',
    catalogVersion: version,
    availability: AccessPermissionAvailability.RESERVED,
  },
  {
    permissionKey: AccessPermissionKey.CRM_CUSTOMERS_MANAGE,
    moduleKey: 'crm',
    action: 'manage',
    description: 'Gestionar expedientes CRM en fase futura',
    catalogVersion: version,
    availability: AccessPermissionAvailability.RESERVED,
  },
  {
    permissionKey: AccessPermissionKey.COMMERCIAL_CATALOG_READ,
    moduleKey: 'commercial',
    action: 'read',
    description: 'Ver catálogo comercial en fase futura',
    catalogVersion: version,
    availability: AccessPermissionAvailability.RESERVED,
  },
  {
    permissionKey: AccessPermissionKey.COMMERCIAL_CATALOG_MANAGE,
    moduleKey: 'commercial',
    action: 'manage',
    description: 'Gestionar catálogo comercial en fase futura',
    catalogVersion: version,
    availability: AccessPermissionAvailability.RESERVED,
  },
  {
    permissionKey: AccessPermissionKey.ASSURANCE_TICKETS_READ,
    moduleKey: 'assurance',
    action: 'read',
    description: 'Ver tickets/PQR en fase futura',
    catalogVersion: version,
    availability: AccessPermissionAvailability.RESERVED,
  },
  {
    permissionKey: AccessPermissionKey.ASSURANCE_TICKETS_MANAGE,
    moduleKey: 'assurance',
    action: 'manage',
    description: 'Gestionar tickets/PQR en fase futura',
    catalogVersion: version,
    availability: AccessPermissionAvailability.RESERVED,
  },
  {
    permissionKey: AccessPermissionKey.INVENTORY_STOCK_READ,
    moduleKey: 'inventory',
    action: 'read',
    description: 'Ver inventario futuro',
    catalogVersion: version,
    availability: AccessPermissionAvailability.RESERVED,
  },
  {
    permissionKey: AccessPermissionKey.INVENTORY_STOCK_MANAGE,
    moduleKey: 'inventory',
    action: 'manage',
    description: 'Gestionar inventario futuro',
    catalogVersion: version,
    availability: AccessPermissionAvailability.RESERVED,
  },
  {
    permissionKey: AccessPermissionKey.BILLING_PAYMENTS_READ,
    moduleKey: 'billing',
    action: 'read',
    description: 'Ver recaudos futuros',
    catalogVersion: version,
    availability: AccessPermissionAvailability.RESERVED,
  },
  {
    permissionKey: AccessPermissionKey.BILLING_PAYMENTS_REGISTER,
    moduleKey: 'billing',
    action: 'register',
    description: 'Registrar recaudo futuro',
    catalogVersion: version,
    availability: AccessPermissionAvailability.RESERVED,
  },
  {
    permissionKey: AccessPermissionKey.BILLING_INVOICES_READ,
    moduleKey: 'billing',
    action: 'read',
    description: 'Ver facturas futuras',
    catalogVersion: version,
    availability: AccessPermissionAvailability.RESERVED,
  },
  {
    permissionKey: AccessPermissionKey.BILLING_INVOICES_MANAGE,
    moduleKey: 'billing',
    action: 'manage',
    description: 'Gestionar facturación futura',
    catalogVersion: version,
    availability: AccessPermissionAvailability.RESERVED,
  },
];

export const ROLE_ASSIGNABLE_PERMISSION_MATRIX: Record<UserRole, AccessPermissionKey[]> = {
  [UserRole.ADMIN]: MOD00_ACCESS_V1_CATALOG.filter(
    (entry) => entry.availability === AccessPermissionAvailability.ASSIGNABLE,
  ).map((entry) => entry.permissionKey),
  [UserRole.NOC]: [
    AccessPermissionKey.SETTINGS_READ,
    AccessPermissionKey.ORGANIZATION_SITES_READ,
    AccessPermissionKey.WFM_SCHEDULE_READ,
    AccessPermissionKey.OPERATIONS_EXECUTION_ORDERS_READ,
    AccessPermissionKey.OPERATIONS_EXECUTION_ORDERS_SUPERVISE,
    AccessPermissionKey.OPERATIONS_TASKS_READ,
    AccessPermissionKey.OPERATIONS_TASKS_MANAGE,
  ],
  [UserRole.SUPPORT]: [
    AccessPermissionKey.SETTINGS_READ,
    AccessPermissionKey.ORGANIZATION_SITES_READ,
    AccessPermissionKey.USERS_READ,
    AccessPermissionKey.WFM_SCHEDULE_READ,
    AccessPermissionKey.OPERATIONS_EXECUTION_ORDERS_READ,
    AccessPermissionKey.OPERATIONS_TASKS_READ,
    AccessPermissionKey.OPERATIONS_TASKS_MANAGE,
  ],
  [UserRole.SALES]: [
    AccessPermissionKey.SETTINGS_READ,
    AccessPermissionKey.ORGANIZATION_SITES_READ,
    AccessPermissionKey.OPERATIONS_TASKS_READ,
    AccessPermissionKey.OPERATIONS_TASKS_MANAGE,
  ],
  [UserRole.TECHNICIAN]: [
    AccessPermissionKey.SETTINGS_READ,
    AccessPermissionKey.ORGANIZATION_SITES_READ,
    AccessPermissionKey.WFM_SCHEDULE_READ,
    AccessPermissionKey.WFM_WORK_ORDERS_EXECUTE,
    AccessPermissionKey.OPERATIONS_EXECUTION_ORDERS_READ,
    AccessPermissionKey.OPERATIONS_EXECUTION_ORDERS_EXECUTE,
    AccessPermissionKey.OPERATIONS_TASKS_READ,
    AccessPermissionKey.OPERATIONS_TASKS_MANAGE,
  ],
  [UserRole.ACCOUNTANT]: [
    AccessPermissionKey.SETTINGS_READ,
    AccessPermissionKey.ORGANIZATION_SITES_READ,
  ],
  [UserRole.HR]: [
    AccessPermissionKey.SETTINGS_READ,
    AccessPermissionKey.ORGANIZATION_SITES_READ,
    AccessPermissionKey.USERS_READ,
  ],
  [UserRole.SUBSCRIBER]: [],
  [UserRole.CONTRACTOR]: [
    AccessPermissionKey.SETTINGS_READ,
    AccessPermissionKey.ORGANIZATION_SITES_READ,
    AccessPermissionKey.WFM_SCHEDULE_READ,
    AccessPermissionKey.WFM_WORK_ORDERS_EXECUTE,
    AccessPermissionKey.OPERATIONS_EXECUTION_ORDERS_READ,
    AccessPermissionKey.OPERATIONS_EXECUTION_ORDERS_EXECUTE,
    AccessPermissionKey.OPERATIONS_TASKS_READ,
  ],
  [UserRole.PARTNER]: [],
  [UserRole.AUDITOR]: [
    AccessPermissionKey.SETTINGS_READ,
    AccessPermissionKey.ORGANIZATION_SITES_READ,
    AccessPermissionKey.USERS_READ,
    AccessPermissionKey.ACCESS_PERMISSIONS_READ,
    AccessPermissionKey.ACCESS_PROFILES_READ,
  ],
  [UserRole.INVESTOR]: [],
};

export const MOD00_ACCESS_V1_SYSTEM_ROLE_TEMPLATES: SystemRoleTemplateDefinition[] = [
  {
    name: 'Administrador general',
    description: 'Plantilla inicial para la administración general de la empresa.',
    baseRoleConstraint: UserRole.ADMIN,
    permissionKeys: ROLE_ASSIGNABLE_PERMISSION_MATRIX[UserRole.ADMIN],
  },
  {
    name: 'Monitoreo operativo',
    description: 'Plantilla inicial para monitoreo operativo.',
    baseRoleConstraint: UserRole.NOC,
    permissionKeys: ROLE_ASSIGNABLE_PERMISSION_MATRIX[UserRole.NOC],
  },
  {
    name: 'Soporte inicial',
    description: 'Plantilla inicial para soporte operativo.',
    baseRoleConstraint: UserRole.SUPPORT,
    permissionKeys: ROLE_ASSIGNABLE_PERMISSION_MATRIX[UserRole.SUPPORT],
  },
  {
    name: 'Técnico de campo',
    description: 'Plantilla inicial para agenda y ejecucion de trabajo de campo.',
    baseRoleConstraint: UserRole.TECHNICIAN,
    permissionKeys: ROLE_ASSIGNABLE_PERMISSION_MATRIX[UserRole.TECHNICIAN],
  },
  {
    name: 'Contratista',
    description: 'Plantilla inicial para operacion de campo limitada.',
    baseRoleConstraint: UserRole.CONTRACTOR,
    permissionKeys: ROLE_ASSIGNABLE_PERMISSION_MATRIX[UserRole.CONTRACTOR],
  },
  {
    name: 'Auditor',
    description: 'Plantilla inicial de consulta para auditoría.',
    baseRoleConstraint: UserRole.AUDITOR,
    permissionKeys: ROLE_ASSIGNABLE_PERMISSION_MATRIX[UserRole.AUDITOR],
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// MOD00_ACCESS_V2 — catálogo, matriz y plantillas estándar (PRD §4.3.4 / HLD §6.6)
// ─────────────────────────────────────────────────────────────────────────────

export const MOD00_ACCESS_V2_DEPRECATED_KEYS: AccessPermissionKey[] = [
  AccessPermissionKey.CRM_CUSTOMERS_READ,
  AccessPermissionKey.CRM_CUSTOMERS_MANAGE,
];

export const MOD00_ACCESS_V2_CATALOG: PermissionSeedDefinition[] = [
  {
    permissionKey: AccessPermissionKey.SETTINGS_READ,
    moduleKey: 'settings',
    action: 'read',
    description: 'Ver centro de Configuración',
    catalogVersion: versionV2,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.SETTINGS_MANAGE,
    moduleKey: 'settings',
    action: 'manage',
    description: 'Administrar la configuración general',
    catalogVersion: versionV2,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.ORGANIZATION_SITES_READ,
    moduleKey: 'organization',
    action: 'read',
    description: 'Ver sedes de la empresa',
    catalogVersion: versionV2,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.ORGANIZATION_SITES_MANAGE,
    moduleKey: 'organization',
    action: 'manage',
    description: 'Crear, editar, activar/desactivar y eliminar sedes',
    catalogVersion: versionV2,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.ORGANIZATION_HOURS_MANAGE,
    moduleKey: 'organization',
    action: 'manage',
    description: 'Gestionar horarios institucionales de sedes',
    catalogVersion: versionV2,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.ORGANIZATION_ASSIGNMENTS_MANAGE,
    moduleKey: 'organization',
    action: 'manage',
    description: 'Gestionar asignaciones y responsables de sedes',
    catalogVersion: versionV2,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.USERS_READ,
    moduleKey: 'users',
    action: 'read',
    description: 'Ver usuarios internos de la empresa',
    catalogVersion: versionV2,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.USERS_MANAGE,
    moduleKey: 'users',
    action: 'manage',
    description: 'Crear, editar y desactivar usuarios internos',
    catalogVersion: versionV2,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.ACCESS_PERMISSIONS_READ,
    moduleKey: 'access',
    action: 'read',
    description: 'Ver los accesos disponibles para cada perfil',
    catalogVersion: versionV2,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.ACCESS_PROFILES_READ,
    moduleKey: 'access',
    action: 'read',
    description: 'Ver perfiles de acceso',
    catalogVersion: versionV2,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.ACCESS_PROFILES_MANAGE,
    moduleKey: 'access',
    action: 'manage',
    description: 'Crear, editar y desactivar perfiles de acceso',
    catalogVersion: versionV2,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.ACCESS_ASSIGNMENTS_MANAGE,
    moduleKey: 'access',
    action: 'manage',
    description: 'Asignar perfiles de acceso a usuarios de la empresa',
    catalogVersion: versionV2,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.WFM_SCHEDULE_READ,
    moduleKey: 'wfm',
    action: 'read',
    description: 'Ver agenda de visitas',
    catalogVersion: versionV2,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.WFM_SCHEDULE_MANAGE,
    moduleKey: 'wfm',
    action: 'manage',
    description: 'Gestionar agenda de visitas',
    catalogVersion: versionV2,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.WFM_WORK_ORDERS_EXECUTE,
    moduleKey: 'wfm',
    action: 'execute',
    description: 'Ejecutar órdenes de trabajo asignadas',
    catalogVersion: versionV2,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.OPERATIONS_EXECUTION_ORDERS_READ,
    moduleKey: 'operations',
    action: 'read',
    description: 'Consultar órdenes de ejecución asignadas y supervisadas',
    catalogVersion: versionV2,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.OPERATIONS_EXECUTION_ORDERS_EXECUTE,
    moduleKey: 'operations',
    action: 'execute',
    description: 'Ejecutar actividades, evidencias y cierre de órdenes asignadas',
    catalogVersion: versionV2,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.OPERATIONS_EXECUTION_ORDERS_SUPERVISE,
    moduleKey: 'operations',
    action: 'supervise',
    description: 'Asignar y supervisar órdenes de ejecución',
    catalogVersion: versionV2,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.OPERATIONS_EXECUTION_ORDER_TEMPLATES_READ,
    moduleKey: 'operations',
    action: 'read',
    description: 'Consultar plantillas de ejecución',
    catalogVersion: versionV2,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.OPERATIONS_EXECUTION_ORDER_TEMPLATES_MANAGE,
    moduleKey: 'operations',
    action: 'manage',
    description: 'Administrar versiones de plantillas de ejecución',
    catalogVersion: versionV2,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.OPERATIONS_EXECUTION_EVENTS_REDRIVE,
    moduleKey: 'operations',
    action: 'redrive',
    description: 'Reintentar eventos fallidos de ejecución con ticket operativo',
    catalogVersion: versionV2,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.OPERATIONS_TASKS_READ,
    moduleKey: 'operations',
    action: 'read',
    description: 'Ver tareas operativas de la empresa',
    catalogVersion: versionV2,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.OPERATIONS_TASKS_MANAGE,
    moduleKey: 'operations',
    action: 'manage',
    description: 'Crear, asignar y actualizar tareas operativas',
    catalogVersion: versionV2,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  // ── Nuevas ASSIGNABLE V2 ──
  {
    permissionKey: AccessPermissionKey.CRM_SUBSCRIBERS_READ,
    moduleKey: 'crm',
    action: 'read',
    description: 'Ver Suscriptores',
    catalogVersion: versionV2,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.CRM_SUBSCRIBERS_MANAGE,
    moduleKey: 'crm',
    action: 'manage',
    description: 'Crear y editar Suscriptores',
    catalogVersion: versionV2,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.CRM_EXPEDIENTES_READ,
    moduleKey: 'crm',
    action: 'read',
    description: 'Ver Oportunidades',
    catalogVersion: versionV2,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.CRM_EXPEDIENTES_MANAGE,
    moduleKey: 'crm',
    action: 'manage',
    description: 'Gestionar Oportunidades',
    catalogVersion: versionV2,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.INVENTORY_PURCHASING_READ,
    moduleKey: 'inventory',
    action: 'read',
    description: 'Ver compras y cotizaciones',
    catalogVersion: versionV2,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.INVENTORY_PURCHASING_MANAGE,
    moduleKey: 'inventory',
    action: 'manage',
    description: 'Gestionar compras y cotizaciones',
    catalogVersion: versionV2,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  // ── Promovidas RESERVED→ASSIGNABLE con descripción sin "en fase futura" ──
  {
    permissionKey: AccessPermissionKey.COMMERCIAL_CATALOG_READ,
    moduleKey: 'commercial',
    action: 'read',
    description: 'Ver catálogo comercial',
    catalogVersion: versionV2,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.COMMERCIAL_CATALOG_MANAGE,
    moduleKey: 'commercial',
    action: 'manage',
    description: 'Gestionar catálogo comercial',
    catalogVersion: versionV2,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.ASSURANCE_TICKETS_READ,
    moduleKey: 'assurance',
    action: 'read',
    description: 'Ver tickets y PQR',
    catalogVersion: versionV2,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.ASSURANCE_TICKETS_MANAGE,
    moduleKey: 'assurance',
    action: 'manage',
    description: 'Gestionar tickets y PQR',
    catalogVersion: versionV2,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.INVENTORY_STOCK_READ,
    moduleKey: 'inventory',
    action: 'read',
    description: 'Ver inventario',
    catalogVersion: versionV2,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  {
    permissionKey: AccessPermissionKey.INVENTORY_STOCK_MANAGE,
    moduleKey: 'inventory',
    action: 'manage',
    description: 'Gestionar inventario',
    catalogVersion: versionV2,
    availability: AccessPermissionAvailability.ASSIGNABLE,
  },
  // ── Billing permanece RESERVED ──
  {
    permissionKey: AccessPermissionKey.BILLING_PAYMENTS_READ,
    moduleKey: 'billing',
    action: 'read',
    description: 'Ver recaudos futuros',
    catalogVersion: versionV2,
    availability: AccessPermissionAvailability.RESERVED,
  },
  {
    permissionKey: AccessPermissionKey.BILLING_PAYMENTS_REGISTER,
    moduleKey: 'billing',
    action: 'register',
    description: 'Registrar recaudo futuro',
    catalogVersion: versionV2,
    availability: AccessPermissionAvailability.RESERVED,
  },
  {
    permissionKey: AccessPermissionKey.BILLING_INVOICES_READ,
    moduleKey: 'billing',
    action: 'read',
    description: 'Ver facturas futuras',
    catalogVersion: versionV2,
    availability: AccessPermissionAvailability.RESERVED,
  },
  {
    permissionKey: AccessPermissionKey.BILLING_INVOICES_MANAGE,
    moduleKey: 'billing',
    action: 'manage',
    description: 'Gestionar facturación futura',
    catalogVersion: versionV2,
    availability: AccessPermissionAvailability.RESERVED,
  },
];

export const ROLE_ASSIGNABLE_PERMISSION_MATRIX_V2: Record<UserRole, AccessPermissionKey[]> = {
  [UserRole.ADMIN]: MOD00_ACCESS_V2_CATALOG.filter(
    (entry) => entry.availability === AccessPermissionAvailability.ASSIGNABLE,
  ).map((entry) => entry.permissionKey),
  [UserRole.NOC]: [
    AccessPermissionKey.SETTINGS_READ,
    AccessPermissionKey.ORGANIZATION_SITES_READ,
    AccessPermissionKey.WFM_SCHEDULE_READ,
    AccessPermissionKey.OPERATIONS_EXECUTION_ORDERS_READ,
    AccessPermissionKey.OPERATIONS_EXECUTION_ORDERS_SUPERVISE,
    AccessPermissionKey.OPERATIONS_TASKS_READ,
    AccessPermissionKey.OPERATIONS_TASKS_MANAGE,
    AccessPermissionKey.CRM_SUBSCRIBERS_READ,
    AccessPermissionKey.CRM_EXPEDIENTES_READ,
    AccessPermissionKey.ASSURANCE_TICKETS_READ,
    AccessPermissionKey.ASSURANCE_TICKETS_MANAGE,
    AccessPermissionKey.INVENTORY_STOCK_READ,
    AccessPermissionKey.INVENTORY_STOCK_MANAGE,
    AccessPermissionKey.INVENTORY_PURCHASING_READ,
    AccessPermissionKey.INVENTORY_PURCHASING_MANAGE,
    AccessPermissionKey.COMMERCIAL_CATALOG_READ,
  ],
  [UserRole.SUPPORT]: [
    AccessPermissionKey.SETTINGS_READ,
    AccessPermissionKey.ORGANIZATION_SITES_READ,
    AccessPermissionKey.USERS_READ,
    AccessPermissionKey.WFM_SCHEDULE_READ,
    AccessPermissionKey.OPERATIONS_EXECUTION_ORDERS_READ,
    AccessPermissionKey.OPERATIONS_TASKS_READ,
    AccessPermissionKey.OPERATIONS_TASKS_MANAGE,
    AccessPermissionKey.CRM_SUBSCRIBERS_READ,
    AccessPermissionKey.CRM_SUBSCRIBERS_MANAGE,
    AccessPermissionKey.CRM_EXPEDIENTES_READ,
    AccessPermissionKey.CRM_EXPEDIENTES_MANAGE,
    AccessPermissionKey.ASSURANCE_TICKETS_READ,
    AccessPermissionKey.ASSURANCE_TICKETS_MANAGE,
    AccessPermissionKey.INVENTORY_STOCK_READ,
    AccessPermissionKey.INVENTORY_STOCK_MANAGE,
    AccessPermissionKey.INVENTORY_PURCHASING_READ,
    AccessPermissionKey.INVENTORY_PURCHASING_MANAGE,
    AccessPermissionKey.COMMERCIAL_CATALOG_READ,
  ],
  [UserRole.SALES]: [
    AccessPermissionKey.SETTINGS_READ,
    AccessPermissionKey.ORGANIZATION_SITES_READ,
    AccessPermissionKey.OPERATIONS_TASKS_READ,
    AccessPermissionKey.OPERATIONS_TASKS_MANAGE,
    AccessPermissionKey.CRM_SUBSCRIBERS_READ,
    AccessPermissionKey.CRM_SUBSCRIBERS_MANAGE,
    AccessPermissionKey.CRM_EXPEDIENTES_READ,
    AccessPermissionKey.CRM_EXPEDIENTES_MANAGE,
    AccessPermissionKey.COMMERCIAL_CATALOG_READ,
  ],
  [UserRole.TECHNICIAN]: [
    AccessPermissionKey.SETTINGS_READ,
    AccessPermissionKey.ORGANIZATION_SITES_READ,
    AccessPermissionKey.WFM_SCHEDULE_READ,
    AccessPermissionKey.WFM_WORK_ORDERS_EXECUTE,
    AccessPermissionKey.OPERATIONS_EXECUTION_ORDERS_READ,
    AccessPermissionKey.OPERATIONS_EXECUTION_ORDERS_EXECUTE,
    AccessPermissionKey.OPERATIONS_TASKS_READ,
    AccessPermissionKey.OPERATIONS_TASKS_MANAGE,
    AccessPermissionKey.CRM_SUBSCRIBERS_READ,
    AccessPermissionKey.ASSURANCE_TICKETS_READ,
    AccessPermissionKey.INVENTORY_STOCK_READ,
  ],
  [UserRole.ACCOUNTANT]: [
    AccessPermissionKey.SETTINGS_READ,
    AccessPermissionKey.ORGANIZATION_SITES_READ,
    AccessPermissionKey.CRM_SUBSCRIBERS_READ,
    AccessPermissionKey.CRM_SUBSCRIBERS_MANAGE,
    AccessPermissionKey.COMMERCIAL_CATALOG_READ,
    AccessPermissionKey.COMMERCIAL_CATALOG_MANAGE,
  ],
  [UserRole.HR]: [
    AccessPermissionKey.SETTINGS_READ,
    AccessPermissionKey.ORGANIZATION_SITES_READ,
    AccessPermissionKey.USERS_READ,
  ],
  [UserRole.SUBSCRIBER]: [],
  [UserRole.CONTRACTOR]: [
    AccessPermissionKey.SETTINGS_READ,
    AccessPermissionKey.ORGANIZATION_SITES_READ,
    AccessPermissionKey.WFM_SCHEDULE_READ,
    AccessPermissionKey.WFM_WORK_ORDERS_EXECUTE,
    AccessPermissionKey.OPERATIONS_EXECUTION_ORDERS_READ,
    AccessPermissionKey.OPERATIONS_EXECUTION_ORDERS_EXECUTE,
    AccessPermissionKey.OPERATIONS_TASKS_READ,
    AccessPermissionKey.ASSURANCE_TICKETS_READ,
  ],
  [UserRole.PARTNER]: [],
  [UserRole.AUDITOR]: [
    AccessPermissionKey.SETTINGS_READ,
    AccessPermissionKey.ORGANIZATION_SITES_READ,
    AccessPermissionKey.USERS_READ,
    AccessPermissionKey.ACCESS_PERMISSIONS_READ,
    AccessPermissionKey.ACCESS_PROFILES_READ,
    AccessPermissionKey.CRM_SUBSCRIBERS_READ,
    AccessPermissionKey.CRM_EXPEDIENTES_READ,
    AccessPermissionKey.ASSURANCE_TICKETS_READ,
    AccessPermissionKey.INVENTORY_STOCK_READ,
    AccessPermissionKey.INVENTORY_PURCHASING_READ,
    AccessPermissionKey.COMMERCIAL_CATALOG_READ,
  ],
  [UserRole.INVESTOR]: [],
};

export const MOD00_ACCESS_V2_SYSTEM_ROLE_TEMPLATES: SystemRoleTemplateDefinition[] = [
  {
    name: 'Administrador general',
    description: 'Plantilla estándar para administración general (MOD00_ACCESS_V2).',
    baseRoleConstraint: UserRole.ADMIN,
    permissionKeys: ROLE_ASSIGNABLE_PERMISSION_MATRIX_V2[UserRole.ADMIN],
  },
  {
    name: 'Acceso estándar NOC',
    description: 'Plantilla estándar NOC (MOD00_ACCESS_V2).',
    baseRoleConstraint: UserRole.NOC,
    permissionKeys: ROLE_ASSIGNABLE_PERMISSION_MATRIX_V2[UserRole.NOC],
  },
  {
    name: 'Acceso estándar Soporte',
    description: 'Plantilla estándar Soporte (MOD00_ACCESS_V2).',
    baseRoleConstraint: UserRole.SUPPORT,
    permissionKeys: ROLE_ASSIGNABLE_PERMISSION_MATRIX_V2[UserRole.SUPPORT],
  },
  {
    name: 'Acceso estándar Comercial',
    description: 'Plantilla estándar Comercial (MOD00_ACCESS_V2).',
    baseRoleConstraint: UserRole.SALES,
    permissionKeys: ROLE_ASSIGNABLE_PERMISSION_MATRIX_V2[UserRole.SALES],
  },
  {
    name: 'Acceso estándar Técnico',
    description: 'Plantilla estándar Técnico (MOD00_ACCESS_V2).',
    baseRoleConstraint: UserRole.TECHNICIAN,
    permissionKeys: ROLE_ASSIGNABLE_PERMISSION_MATRIX_V2[UserRole.TECHNICIAN],
  },
  {
    name: 'Acceso estándar Contable',
    description: 'Plantilla estándar Contable (MOD00_ACCESS_V2).',
    baseRoleConstraint: UserRole.ACCOUNTANT,
    permissionKeys: ROLE_ASSIGNABLE_PERMISSION_MATRIX_V2[UserRole.ACCOUNTANT],
  },
  {
    name: 'Acceso estándar RRHH',
    description: 'Plantilla estándar RRHH (MOD00_ACCESS_V2).',
    baseRoleConstraint: UserRole.HR,
    permissionKeys: ROLE_ASSIGNABLE_PERMISSION_MATRIX_V2[UserRole.HR],
  },
  {
    name: 'Acceso estándar Contratista',
    description: 'Plantilla estándar Contratista (MOD00_ACCESS_V2).',
    baseRoleConstraint: UserRole.CONTRACTOR,
    permissionKeys: ROLE_ASSIGNABLE_PERMISSION_MATRIX_V2[UserRole.CONTRACTOR],
  },
  {
    name: 'Acceso estándar Auditoría',
    description: 'Plantilla estándar Auditoría (MOD00_ACCESS_V2).',
    baseRoleConstraint: UserRole.AUDITOR,
    permissionKeys: ROLE_ASSIGNABLE_PERMISSION_MATRIX_V2[UserRole.AUDITOR],
  },
];
