export enum OrganizationSiteResponsibility {
  ADMINISTRATIVE = 'ADMINISTRATIVE',
  INVENTORY = 'INVENTORY',
  COLLECTION = 'COLLECTION',
  FIELD_OPERATIONS = 'FIELD_OPERATIONS',
  CUSTOMER_SERVICE = 'CUSTOMER_SERVICE',
}
