export enum OrganizationSiteType {
  OFFICE = 'OFFICE',
  WAREHOUSE = 'WAREHOUSE',
  TECH_BASE = 'TECH_BASE',
  CUSTOMER_SERVICE = 'CUSTOMER_SERVICE',
  COLLECTION_POINT = 'COLLECTION_POINT',
  NOC = 'NOC',
  MIXED = 'MIXED',
}
