export enum AcquisitionChannel {
  OFICINA = 'OFICINA',
  WHATSAPP = 'WHATSAPP',
  LLAMADA_ENTRANTE = 'LLAMADA_ENTRANTE',
  LLAMADA_SALIENTE = 'LLAMADA_SALIENTE',
  REDES_SOCIALES = 'REDES_SOCIALES',
  REFERIDO_CLIENTE = 'REFERIDO_CLIENTE',
  REFERIDO_VENDEDOR = 'REFERIDO_VENDEDOR',
  REFERIDO_TECNICO = 'REFERIDO_TECNICO',
  PUERTA_A_PUERTA = 'PUERTA_A_PUERTA',
  EVENTO = 'EVENTO',
  WEB = 'WEB',
  OTRO = 'OTRO',
}
