/**
 * Estados del pipeline de expediente unico progresivo.
 *
 * Consolidado de 12 a 8 estados (ADR-026):
 * - Eliminados: CONTACTADO, PENDIENTE_DATOS, VIABLE_COMERCIALMENTE, PENDIENTE_DECISION
 * - CONTACTADO y PENDIENTE_DATOS absorbidos por PRECALIFICADO
 * - VIABLE_COMERCIALMENTE absorbido por VALIDANDO_COBERTURA
 * - PENDIENTE_DECISION absorbido por EN_COTIZACION
 */
export enum ExpedienteStatus {
  NUEVO_POTENCIAL = 'NUEVO_POTENCIAL',
  PRECALIFICADO = 'PRECALIFICADO',
  VALIDANDO_COBERTURA = 'VALIDANDO_COBERTURA',
  EN_COTIZACION = 'EN_COTIZACION',
  LISTO_PARA_INSTALACION = 'LISTO_PARA_INSTALACION',
  INSTALACION_AGENDADA = 'INSTALACION_AGENDADA',
  CLIENTE_ACTIVO = 'CLIENTE_ACTIVO',
  DESCARTADO = 'DESCARTADO',
}
