/**
 * Estados del pipeline de expediente unico progresivo.
 */
export enum ExpedienteStatus {
  NUEVO_POTENCIAL = 'NUEVO_POTENCIAL',
  CONTACTADO = 'CONTACTADO',
  PENDIENTE_DATOS = 'PENDIENTE_DATOS',
  PRECALIFICADO = 'PRECALIFICADO',
  VALIDANDO_COBERTURA = 'VALIDANDO_COBERTURA',
  VIABLE_COMERCIALMENTE = 'VIABLE_COMERCIALMENTE',
  EN_COTIZACION = 'EN_COTIZACION',
  PENDIENTE_DECISION = 'PENDIENTE_DECISION',
  LISTO_PARA_INSTALACION = 'LISTO_PARA_INSTALACION',
  INSTALACION_AGENDADA = 'INSTALACION_AGENDADA',
  CLIENTE_ACTIVO = 'CLIENTE_ACTIVO',
  DESCARTADO = 'DESCARTADO',
}
