export enum VisitRequestStatus {
  PENDING = 'PENDING',
  NEEDS_CONTEXT = 'NEEDS_CONTEXT',
  READY_TO_SCHEDULE = 'READY_TO_SCHEDULE',
  SCHEDULED = 'SCHEDULED',
  CANCELLED = 'CANCELLED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
}
