export enum VisitRequestStatus {
  PENDING = 'PENDING',
  NEEDS_CONTEXT = 'NEEDS_CONTEXT',
  READY_TO_SCHEDULE = 'READY_TO_SCHEDULE',
  SCHEDULED = 'SCHEDULED',
  IN_EXECUTION = 'IN_EXECUTION',
  CLOSED = 'CLOSED',
  REQUIRES_RESCHEDULE = 'REQUIRES_RESCHEDULE',
  CANCELLED = 'CANCELLED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
}
