export enum ExecutionOrderStatus {
  CREATED = 'CREATED',
  ASSIGNED = 'ASSIGNED',
  EN_ROUTE = 'EN_ROUTE',
  IN_PROGRESS = 'IN_PROGRESS',
  BLOCKED = 'BLOCKED',
  COMPLETED = 'COMPLETED',
  COMPLETED_WITH_OBSERVATIONS = 'COMPLETED_WITH_OBSERVATIONS',
  NOT_EXECUTED = 'NOT_EXECUTED',
  CANCELLED = 'CANCELLED',
}
