export enum ProspectCaseStatus {
  POTENTIAL = 'POTENTIAL',
  PROSPECT = 'PROSPECT',
  INSTALLATION_SCHEDULED = 'INSTALLATION_SCHEDULED',
  TECH_VISIT = 'TECH_VISIT',
  ACTIVE_CUSTOMER = 'ACTIVE_CUSTOMER',
  RESCHEDULED = 'RESCHEDULED',
  IN_REVIEW = 'IN_REVIEW',
  NOT_VIABLE = 'NOT_VIABLE',
}
