export enum AccessPermissionKey {
  SETTINGS_READ = 'settings.read',
  SETTINGS_MANAGE = 'settings.manage',
  ORGANIZATION_SITES_READ = 'organization.sites.read',
  ORGANIZATION_SITES_MANAGE = 'organization.sites.manage',
  ORGANIZATION_HOURS_MANAGE = 'organization.hours.manage',
  ORGANIZATION_ASSIGNMENTS_MANAGE = 'organization.assignments.manage',
  USERS_READ = 'users.read',
  USERS_MANAGE = 'users.manage',
  ACCESS_PERMISSIONS_READ = 'access.permissions.read',
  ACCESS_PROFILES_READ = 'access.profiles.read',
  ACCESS_PROFILES_MANAGE = 'access.profiles.manage',
  ACCESS_ASSIGNMENTS_MANAGE = 'access.assignments.manage',
  WFM_SCHEDULE_READ = 'wfm.schedule.read',
  WFM_SCHEDULE_MANAGE = 'wfm.schedule.manage',
  /**
   * @deprecated Usar {@link OPERATIONS_EXECUTION_ORDERS_EXECUTE}.
   * Retirable cuando cero consumidores y Task 10 complete (ver INFORME-MOD11-FLOW-CABLEADO-v1.0.md §9.3).
   */
  WFM_WORK_ORDERS_EXECUTE = 'wfm.work_orders.execute',
  OPERATIONS_EXECUTION_ORDERS_READ = 'operations.execution_orders.read',
  OPERATIONS_EXECUTION_ORDERS_EXECUTE = 'operations.execution_orders.execute',
  OPERATIONS_EXECUTION_ORDERS_SUPERVISE = 'operations.execution_orders.supervise',
  OPERATIONS_EXECUTION_ORDER_TEMPLATES_READ = 'operations.execution_order_templates.read',
  OPERATIONS_EXECUTION_ORDER_TEMPLATES_MANAGE = 'operations.execution_order_templates.manage',
  OPERATIONS_EXECUTION_EVENTS_REDRIVE = 'operations.execution_events.redrive',
  OPERATIONS_TASKS_READ = 'operations.tasks.read',
  OPERATIONS_TASKS_MANAGE = 'operations.tasks.manage',
  CRM_CUSTOMERS_READ = 'crm.customers.read',
  CRM_CUSTOMERS_MANAGE = 'crm.customers.manage',
  COMMERCIAL_CATALOG_READ = 'commercial.catalog.read',
  COMMERCIAL_CATALOG_MANAGE = 'commercial.catalog.manage',
  ASSURANCE_TICKETS_READ = 'assurance.tickets.read',
  ASSURANCE_TICKETS_MANAGE = 'assurance.tickets.manage',
  INVENTORY_STOCK_READ = 'inventory.stock.read',
  INVENTORY_STOCK_MANAGE = 'inventory.stock.manage',
  BILLING_PAYMENTS_READ = 'billing.payments.read',
  BILLING_PAYMENTS_REGISTER = 'billing.payments.register',
  BILLING_INVOICES_READ = 'billing.invoices.read',
  BILLING_INVOICES_MANAGE = 'billing.invoices.manage',
}
