export declare enum TicketTimelineEventType {
    CREATED = "CREATED",
    ASSIGNED = "ASSIGNED",
    REASSIGNED = "REASSIGNED",
    STATUS_CHANGED = "STATUS_CHANGED",
    COMMENT_ADDED = "COMMENT_ADDED",
    FIELD_SERVICE_REQUESTED = "FIELD_SERVICE_REQUESTED",
    WORK_ORDER_LINKED = "WORK_ORDER_LINKED",
    SLA_BREACHED = "SLA_BREACHED",
    PQR_DEADLINE_SET = "PQR_DEADLINE_SET",
    PRIORITY_CHANGED = "PRIORITY_CHANGED",
    CLOSED = "CLOSED"
}
//# sourceMappingURL=ticket-timeline-event-type.enum.d.ts.map