export const PLATFORM_UI_COPY = {
  navigation: {
    home: 'Centro de control',
    tenants: 'Empresas',
    users: 'Usuarios internos',
    audit: 'Historial de cambios',
    settings: 'Plataforma',
    profile: 'Mi cuenta',
  },
  shell: {
    workspace: 'Plataforma iWana',
    workspaceSubtitle: 'Consola de plataforma.',
    openMenu: 'Abrir menú',
    closeMenu: 'Cerrar menú',
    expandSidebar: 'Expandir panel lateral',
    collapseSidebar: 'Contraer panel lateral',
    goHome: 'Ir al centro de control',
    navLandmark: 'Navegación principal',
    menuLandmark: 'Menú principal',
  },
  dashboard: {
    title: 'Centro de control',
    subtitle: 'Salud de plataforma, altas en curso y lo que requiere atención.',
    summaryEyebrow: 'Resumen operativo',
    loading: 'Cargando el centro de control',
    chipActive: 'Activas',
    chipProvisioning: 'En configuración',
    chipAttention: 'Requieren atención',
    chipWeeklyChanges: 'Cambios esta semana',
    viewActiveCompanies: 'Ver empresas activas',
    viewProvisioningCompanies: 'Ver empresas en configuración',
    viewStatusBreakdown: 'Ver el desglose por estado',
    statusEyebrow: 'Directorio',
    statusTitle: 'Empresas por estado',
    statusTotalLabel: 'En el directorio',
    statusFooter: 'Ver todas las empresas',
    statusEmpty: 'Aún no hay empresas registradas.',
    statusEmptyHint:
      'Cuando registres la primera, verás aquí cuántas operan, cuáles siguen en alta y cuáles pedirán revisión.',
    statusEmptyCta: 'Registrar primera empresa',
    statusActive: 'Activas',
    statusProvisioning: 'En configuración',
    statusFailed: 'Con error',
    statusSuspended: 'Suspendidas',
    statusInactive: 'Inactivas',
    statusMarkedForDeletion: 'En eliminación',
    statusHintActive: 'Ya operan con normalidad.',
    statusHintProvisioning: 'Alta en curso; aún no están listas.',
    statusHintFailed: 'La puesta en marcha no terminó.',
    statusHintSuspended: 'Acceso detenido por el equipo.',
    statusHintInactive: 'Sin operación por ahora.',
    statusHintDeletion: 'Salida en proceso.',
    activityTitle: 'Actividad reciente',
    activityFooter: 'Abrir historial',
    activityEmpty: 'Aún no hay cambios recientes para mostrar.',
    directoryError: 'No pudimos cargar el directorio. Reintenta en unos minutos.',
    activityError: 'No pudimos cargar la actividad reciente.',
    retry: 'Reintentar',
  },
  tenants: {
    subtitle: 'Estado, contacto y última actualización de cada empresa.',
    eyebrow: 'Directorio',
    tableTitle: 'Directorio',
    searchPlaceholder: 'Buscar por empresa o contacto…',
    loading: 'Cargando el directorio',
    newCompany: 'Nueva empresa',
    firstCompanyCta: 'Registrar primera empresa',
    emptyParkTitle: 'Aún no hay empresas registradas',
    emptyParkHint: 'Cuando registres la primera empresa, aparecerá aquí con su estado operativo.',
    emptyFilterTitle: 'Sin empresas con estos filtros',
    emptyFilterHint:
      'Ajusta la búsqueda o el estado, o limpia el filtro para ver todo el directorio.',
    focusDirectory: 'Ir al directorio',
    suspendSuccess: 'Empresa suspendida.',
    activateSuccess: 'Empresa reactivada.',
    retrySuccess: 'Reintento de alta enviado.',
    actionError: 'No pudimos completar la acción. Reintenta en unos minutos.',
    notificationsTitle: 'Avisos del directorio',
    notificationsSubtitle: 'Empresas que conviene revisar ahora.',
    notificationsEmpty: 'No hay avisos por ahora.',
    notificationsError: 'No pudimos cargar los avisos. Reintenta en unos minutos.',
    notificationsUpdated: 'Actualizada',
  },
  users: {
    title: 'Usuarios internos',
    subtitleIdle: 'Selecciona una empresa para revisar accesos internos.',
    createAction: 'Crear usuario interno',
  },
  audit: {
    title: 'Historial de cambios',
    subtitle: 'Qué cambió el equipo en empresas, accesos y la plataforma.',
    platformSectionTitle: 'Cambios de plataforma',
    platformSectionSubtitle:
      'Lo que hicieron los administradores en empresas, usuarios internos y configuración.',
    tenantSectionTitle: 'Cambios por empresa',
    tenantSectionSubtitle: 'Revisa qué ocurrió dentro de la empresa seleccionada.',
    loadError: 'No pudimos cargar el historial. Reintenta en unos minutos.',
    pageSizeLabel: 'Cambios por página',
    scopeLabel: 'Ámbito del historial',
    modeReading: 'Lectura',
    modeDetail: 'Detalle',
    download: 'Descargar',
    downloading: 'Descargando…',
    downloadError: 'No pudimos descargar el archivo. Reintenta en unos minutos.',
    downloadTruncated: 'La descarga se limitó a 5000 cambios.',
    window24h: 'Últimas 24 h',
    window7d: 'Últimos 7 días',
    criticalChanges: 'Cambios críticos',
    accesses: 'Accesos',
    accessAndSecurity: 'Acceso y seguridad',
    companiesWithChanges: 'Empresas con cambios',
    whoChanged: 'Quién cambió',
    emptyPark: 'Sin actividad registrada',
    emptyParkHint: 'Cuando ocurra un cambio, aparecerá aquí.',
    emptyFiltered: 'Sin cambios con estos filtros',
    emptyFilteredHint: 'Ajusta la acción o el rango de fechas, o limpia los filtros.',
    emptySummaryPreset: 'Sin cambios en el lote del resumen con este filtro',
    emptySummaryPresetHint: 'Quita el filtro del resumen para ver todos los cambios.',
    summaryFilterChip: 'Mostrando: {label} · lote del resumen',
    summaryFilterClear: 'Quitar filtro',
    expandDetail: 'Ver detalle',
    collapseDetail: 'Ocultar',
    severityNormal: 'Normal',
    severityCritical: 'Crítico',
    severityMedium: 'Medio',
    summaryEyebrow: 'Resumen',
    focusTable: 'Ir al listado de cambios',
    tableTitle: 'Listado de cambios',
    allActions: 'Todas las acciones',
    fieldLabels: {
      firstName: 'Nombre',
      lastName: 'Apellido',
      name: 'Nombre',
      email: 'Correo',
      status: 'Estado',
      role: 'Categoría base',
      isActive: 'Activo',
      password: 'Contraseña',
      mfaEnabled: 'Verificación en dos pasos',
      slug: 'Identificador interno',
      schemaName: 'Identificador interno',
      plan: 'Plan',
      companyName: 'Empresa',
      legalName: 'Razón social',
    },
    actionLabels: {
      create: 'Alta',
      update: 'Cambio',
      delete: 'Baja',
      suspend: 'Suspensión',
      activate: 'Reactivación',
      login: 'Inicio de sesión',
      logout: 'Cierre de sesión',
      login_failed: 'Acceso fallido',
      account_locked: 'Acceso bloqueado',
      password_changed: 'Cambio de contraseña',
      password_reset_requested: 'Pedido de contraseña',
      password_reset_completed: 'Contraseña restablecida',
      mfa_enabled: 'Verificación en dos pasos activada',
      mfa_disabled: 'Verificación en dos pasos desactivada',
      mfa_setup_initiated: 'Inicio de verificación en dos pasos',
      mfa_setup: 'Verificación en dos pasos',
      mfa_verified: 'Verificación en dos pasos confirmada',
      tenant_provisioned: 'Puesta en marcha',
      tenant_suspended: 'Empresa suspendida',
      tenant_activated: 'Empresa reactivada',
      provision: 'Puesta en marcha',
      retry: 'Reintento',
      refresh: 'Renovación de sesión',
      email_verified: 'Correo verificado',
    },
    entityTypeLabels: {
      tenant: 'empresa',
      user: 'usuario interno',
      settings: 'configuración',
      platform: 'plataforma',
      role: 'categoría base',
      accessprofile: 'perfil de acceso',
      expediente: 'oportunidad',
    },
    actorFallback: 'Alguien del equipo',
    actionVerbs: {
      create: 'registró',
      update: 'actualizó',
      delete: 'eliminó',
      suspend: 'suspendió',
      activate: 'reactivó',
      login: 'inició sesión',
      logout: 'cerró sesión',
      login_failed: 'no pudo iniciar sesión',
      account_locked: 'bloqueó el acceso',
      password_changed: 'cambió la contraseña',
      password_reset_requested: 'pidió restablecer la contraseña',
      password_reset_completed: 'restableció la contraseña',
      mfa_enabled: 'activó la verificación en dos pasos',
      mfa_disabled: 'desactivó la verificación en dos pasos',
      mfa_setup_initiated: 'empezó la verificación en dos pasos',
      mfa_setup: 'configuró la verificación en dos pasos',
      mfa_verified: 'confirmó la verificación en dos pasos',
      tenant_provisioned: 'puso en marcha',
      tenant_suspended: 'suspendió',
      tenant_activated: 'reactivó',
      provision: 'puso en marcha',
      retry: 'reintentó',
      refresh: 'renovó la sesión',
      email_verified: 'verificó el correo',
    },
    entityPhrases: {
      tenant: 'una empresa',
      user: 'un usuario interno',
      platformuser: 'un usuario interno',
      settings: 'la configuración',
      tenantsettings: 'la configuración de la empresa',
      platform: 'la plataforma',
      role: 'una categoría base',
      accessprofile: 'un perfil de acceso',
      expediente: 'una oportunidad',
      expedienterecord: 'una oportunidad',
      session: 'la sesión',
      auditlog: 'el historial',
    },
  },
  settings: {
    subtitle: 'Identidad de la consola y seguridad de tu acceso.',
    tenantsBoundary: 'La configuración de cada empresa está en Empresas.',
    tabsAriaLabel: 'Configuración de plataforma',
    tabIdentity: 'Identidad',
    tabSecurity: 'Seguridad',
    identity: {
      title: 'Identidad de la consola',
      help: 'Logo, fondos de acceso y nombres públicos. No cambia la identidad de cada empresa.',
      loading: 'Cargando identidad de la consola…',
      assetsSection: 'Imágenes de la consola',
      assetsHelp:
        'Haz clic sobre cada vista previa para reemplazar la imagen. Las opciones avanzadas quedan disponibles solo cuando las necesites.',
      logoLabel: 'Logo de consola',
      logoDescription:
        'Se usa en la navegación principal, la cabecera móvil y el acceso administrativo.',
      logoUrlLabel: 'Logo',
      logoImgAlt: 'Logo de plataforma',
      faviconLabel: 'Favicon administrativo',
      faviconDescription: 'Identifica la consola en pestañas del navegador y pantalla de acceso.',
      faviconUrlLabel: 'Favicon',
      faviconImgAlt: 'Favicon de plataforma',
      loginBgLightLabel: 'Fondo de acceso — modo claro',
      loginBgLightDescription:
        'Ambientación principal de la pantalla de acceso cuando el tema claro está activo.',
      loginBgLightUrlLabel: 'Fondo de acceso claro',
      loginBgLightImgAlt: 'Fondo de acceso modo claro',
      loginBgDarkLabel: 'Fondo de acceso — modo oscuro',
      loginBgDarkDescription:
        'Ambientación principal de la pantalla de acceso cuando el tema oscuro está activo.',
      loginBgDarkUrlLabel: 'Fondo de acceso oscuro',
      loginBgDarkImgAlt: 'Fondo de acceso modo oscuro',
      namesSection: 'Nombres e identidad',
      namesHelp: 'Definen cómo se nombra la consola en navegación, acceso y pestaña del navegador.',
      productLabel: 'Producto',
      surfaceLabel: 'Nombre en la consola',
      titleLabel: 'Título de pestaña',
      descriptionLabel: 'Descripción corta',
      previewProduct: 'Producto',
      previewSurface: 'Nombre en la consola',
      previewTitle: 'Título de pestaña',
      previewDescription: 'Descripción corta',
      advancedOptions: 'Opciones avanzadas de la imagen',
      advancedHelp:
        'Usa una URL solo si el archivo ya existe en una ubicación aprobada y no necesitas subirlo desde esta pantalla.',
      changeImage: 'Cambiar imagen',
      uploadImage: 'Subir imagen',
      uploading: 'Subiendo…',
      removeDialogTitle: '¿Eliminar {label}?',
      removeDialogBody: 'Se usará la imagen por defecto de la plataforma.',
      removeCta: 'Eliminar imagen',
      removeConfirm: 'Sí, eliminar',
      cancel: 'Cancelar',
      resetDefaults: 'Restaurar valores por defecto',
      save: 'Guardar cambios',
      retry: 'Reintentar',
      mimeHelpLogo: 'PNG, JPG o WEBP · máx. 1 MB · mín. 240×60.',
      mimeHelpFavicon: 'PNG o ICO · máx. 256 KB · cuadrado, entre 32×32 y 512×512.',
      mimeHelpLoginBg: 'PNG, JPG o WEBP · máx. 5 MB · mín. 1280×720.',
      successSave: 'Identidad guardada.',
      successReset: 'Valores por defecto restaurados.',
      successUpload: 'Imagen aplicada.',
      successRemove: 'Imagen eliminada. Se usa la imagen por defecto.',
      errorLoad: 'No pudimos cargar la identidad de la consola. Reintenta en unos minutos.',
      errorSave: 'No pudimos guardar la identidad. Reintenta en unos minutos.',
      errorUpload: 'No pudimos subir la imagen. Reintenta en unos minutos.',
      errorRemove: 'No pudimos eliminar la imagen. Reintenta en unos minutos.',
      errorReset: 'No pudimos restaurar los valores por defecto. Reintenta en unos minutos.',
      validationProduct: 'El producto debe tener al menos 2 caracteres.',
      validationSurface: 'El nombre en la consola debe tener al menos 2 caracteres.',
      validationTitle: 'El título debe tener al menos 4 caracteres.',
      validationDescription: 'La descripción debe tener al menos 12 caracteres.',
      validationUrl: 'Usa una URL HTTPS o una ruta interna del sistema.',
    },
    security: {
      passwordTitle: 'Cambiar contraseña',
      passwordHelp: 'Cambia la contraseña con la que entras a la consola.',
      currentPassword: 'Contraseña actual',
      newPassword: 'Nueva contraseña',
      confirmPassword: 'Confirmar nueva contraseña',
      passwordCta: 'Actualizar contraseña',
      passwordSuccess: 'Contraseña actualizada.',
      passwordError: 'No pudimos cambiar la contraseña. Reintenta en unos minutos.',
      mfaTitle: 'Verificación en dos pasos',
      mfaHelp: 'Añade un código de tu teléfono al iniciar sesión.',
      mfaStatusOn: 'Activada',
      mfaStatusOff: 'Desactivada',
      mfaLoading: 'Comprobando verificación en dos pasos…',
      mfaStatusLabel: 'Estado actual',
      mfaSetupCta: 'Activar verificación en dos pasos',
      mfaPostSetup: 'Escanea el código QR con tu app de autenticación e ingresa el primer código.',
      mfaQrTitle: 'Código QR para la app de autenticación',
      mfaQrAlt: 'Código QR para la app de autenticación',
      mfaConfirmTitle: 'Confirmar código',
      mfaConfirmCta: 'Confirmar código',
      mfaDisableTitle: 'Desactivar verificación en dos pasos',
      mfaDisableHelp: 'Confirma tu contraseña y un código de tu app de autenticación.',
      mfaDisableCta: 'Desactivar verificación en dos pasos',
      mfaCodeLabel: 'Código de verificación',
      mfaSuccessOn: 'Verificación en dos pasos activada.',
      mfaSuccessOff: 'Verificación en dos pasos desactivada.',
      mfaErrorSetup: 'No pudimos activar la verificación en dos pasos. Reintenta en unos minutos.',
      mfaErrorVerify: 'No pudimos confirmar el código. Reintenta en unos minutos.',
      mfaErrorDisable:
        'No pudimos desactivar la verificación en dos pasos. Reintenta en unos minutos.',
    },
  },
  shared: {
    selectTenant: 'Seleccionar empresa',
    noTenantsAvailable: 'Sin empresas activas',
    chooseTenant: 'Selecciona una empresa',
  },
} as const;

export function getPlatformUsersSubtitle(tenantName: string | null | undefined): string {
  if (!tenantName) {
    return PLATFORM_UI_COPY.users.subtitleIdle;
  }

  return `Gestiona acceso interno de ${tenantName}`;
}
